### ISSUE TITLE
Exit method doesn't work with route parameters

### ISSUE THREAD

**Issue by jmisavage** [mtrpcic/pathjs#1]
I have a route defined as

```
Path.map("#!/clients/:client/:campaign").to(mainFunc).exit(exitFunc);
```

If I go to something like this

```
#!/clients/geico/caveman
```

The exit event will never fire because its searching for `#!/clients/geico/caveman` but only `#!/clients/:client/:campaign` is around.

**Comment by jmisavage** [comment]
I figured out a fix.  I replaced the following lines in the Path.core.route.prototype.run method:

```
if (Path.routes.hasOwnProperty(Path.routes.previous)) {
    if (Path.routes[Path.routes.previous].do_exit !== null) {
        Path.routes[Path.routes.previous].do_exit();
    }
}
```

with

```
if (Path.routes.previous) {
    var previous = Path.match(Path.routes.previous);
    if (previous.do_exit !== null) {
        previous.do_exit();
    }
}
```

Probably not the quickest executing fix, but it does the job and leverages your match method.

**Comment by mtrpcic** [comment]
Thanks for the tip jmisavage.  If you'd like to fork the project and make a pull request for your changes, I'll apply them to master.  If it's not worth the time, I'll just apply it myself.  I'll also look into any way of optimizing it.
