### ISSUE TITLE
Tests fail on Android 2.3.3

### ISSUE THREAD

**Issue by Senne** [mtrpcic/pathjs#14]
The test included with the script fails on Android 2.3.3. I compared the Expected and Actual strings and the first two tokens, F[enter] and F[action],  are not present in the Actual string.

This test confirms a problem I had where functions were not executed when browsing to the root of the webapp with an Android 2.3.3 device.

**Comment by mtrpcic** [comment]
Thank you for posting this, I'll see what can be done to fix this.  I should be able to spend a considerable amount of time on it starting on December 24th until January 3rd, so if a fix is possible it should be in that timeframe.

**Comment by mtrpcic** [comment]
This has been fixed in PathJS version 0.8.1 (committed today).  It was tested on Android 2.3.5 instead of 2.3.3, but the same issue was happening.  Should be fixed all around.
