### ISSUE TITLE
ie9

### ISSUE THREAD

**Issue by mendrik** [mtrpcic/pathjs#18]
http://mtrpcic.github.com/pathjs/html5_basic.html

this doesn't seem to fall back to hash routes in IE9

**Comment by mtrpcic** [comment]
If you view the source for that example, you'll see that I have told it explicitly **not** to fall back to hash routes.  The code used is documented in the last script tag in the `head` tag.

**Comment by mendrik** [comment]
Oops.  My bad, sorry for wasting your time.

**Comment by mtrpcic** [comment]
No problem.
