### ISSUE TITLE
No way to skip navigation to a path...

### ISSUE THREAD

**Issue by digiprop** [mtrpcic/pathjs#19]
There is currently no way to temporarily skip firing the event when navigating to a path.  I have some code in my page that updates the hash manually via the results from an ajax call.  This causes PathJS to fire AGAIN because the hash changed, which causes my code to update the hash, etc...

**Comment by mtrpcic** [comment]
PathJS is meant as a routing platform, and that means the hash change event is used to handle that.  The hash should only be changed if you want your users to be able to navigate back from, and forward to, that state in your web application.  If you are just updating it to store some information, I recommend a different method.  You could have the response of your AJAX call change the route, and have the route change perform the action you're AJAX response is currently doing.

**Comment by digiprop** [comment]
In most cases, we use PathJS exactly as you described (updating the route and causing the ajax request to trigger.)  However there is one case where we need to do this in reverse.  Basically the user clicks on a link and we need data from the server that we don't have yet.  This data includes a search key that tells path to load the correct search on page load.  BackboneJS and other frameworks have a navigate feature that does exactly as i described.  I really like PathJS however and want to keep using path.  I actually built a navigate function in path that skips navigation and resolves the issue that I was having.
