### ISSUE TITLE
iOS 5 Safari Back Button

### ISSUE THREAD

**Issue by giantrobotbee** [mtrpcic/pathjs#24]
This may be out of your hands, but I'm using Path for an app that's designed to be used on mobile devices and I'm running into an odd issue with mobile Safari on iOS 5.

I have my root set with Path.root("#/home")

If I navigate to my site foo.com, I get taken to foo.com/#/home. Everything is gravy. However, if I navigate to a new page and then use the browser back button, I get taken back to foo.com without the hash at the end. It seems that the hash isn't getting written to the history. This works on other normal browsers. However, I was encountering the exact same bug on normal Safari for Mac. The fix seemed to be binding an empty function to the window.onunload event forcing the page to refresh every time the page is reloaded.

`window.onunload = function(){};`

This fixes the problem for desktop Safari and mobile Safari for iOS 4, but in 5, the problem remains.

Wondering if there's a potential fix to be made in Path to compensate for this or if the problem is too deep in Safari to fix.

Thanks for your help!

**Comment by mtrpcic** [comment]
Could you provide an example script that demonstrates this problem?  Do you know if this problem is encountered in iOS 4.x as well, or is it unique to iOS5?  Is it iOS 5.*, or iOS 5.1+?

**Comment by giantrobotbee** [comment]
Sorry for the delayed response. It would seem that this is a mobile Safari problem across the board. I was able to work around it by using pushState (which works marvelously btw).
