### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by jchaney** [mtrpcic/pathjs#3]
This would help DRY out some code so that someone doesn't have to duplicate route maps.

For example ( this is how ExpressJS does it on the server side ): 

```
Path.map("#/venues/:sortorder?").to(function{
    // Then we can do stuff like fn(this.params['sortorder'] || 'default');
});
```

I would happily fork it and submit the changes to make this work, however my javascript-fu is weak. Looking at the code, I couldn't tell how easily this could be accomplished. So this is just a feature request.

**Comment by mtrpcic** [comment]
Thank you for the suggestion, but this feature will not be implemented in PathJS.  PathJS is meant to closely mimic the Rails router, which has specifically defined routes per action.  After thinking on the issue, I've come up with a potential solution to your "default value" issue:

```
// Define your route like so:
Path.map("#/venues/:sort_order").to(function(){
    console.log(this.params["sort_order"]);
}).defaults({
    "sort_order": "ASC"
});

// Then, if you have a link like so:
<a href="#/venues/:sort_order">Venus</a>

// It will check the routes table for defaults, and change the active route to:
#/venues/ASC
```

This solution allows you to set defaults for any particular route, and access a route without having any data beforehand by using that default.  Do you think this solution is a reasonable middle ground to keeping the strict "one route, one action" style of PathJS while providing you access to convenient defaults?

**Comment by jchaney** [comment]
Actually, as of Rails 3 you can do optional parameters in your routes.

```
match 'posts(/new)', :to => 'posts#create'
```

Sends both of the below routes to the same controller. 
/posts
/posts/new

I guess I just think that the below routes:
/venues
/venues/ASC
/venues/DESC

Looks more RESTful than:
/venues/default
/venues/ASC
/venues/DESC

But it really only applies in certain situations. One thing I should have mentioned is that in my original example, adding the '?' is what makes it optional, otherwise if the '?' was not added to the match, it would require that param to exist to match that route. So I think everyone wins in that scenario. Either way, I'm going to continue to use your lib, I think it's excellent. I just may have to duplicate a little more code. Thanks!

**Comment by mtrpcic** [comment]
This feature is under development.

**Comment by mtrpcic** [comment]
This feature was added as part of commit `deb9cba60b7f32aa1d62`, which is PathJS version 0.6.  View the readme for details on how to implement these routes in your application.
