### ISSUE TITLE
Form posts

### ISSUE THREAD

**Issue by danielwertheim** [mtrpcic/pathjs#30]
Hi,

sorry for using an "issue" like this but can't find any contact info. How are you supposed to handle form posts? Can't find any route setup that will listen on POSTs.

//Daniel

**Comment by mtrpcic** [comment]
Right now PathJS doesn't support posting to client-side routes, and to be honest, you're the first person to bring it up.  I'll see if there's anything that can be done.

**Comment by danielwertheim** [comment]
I was switching out a Sammy application where it was needed but it
turns out I don't need it with PathJs. Better of without it.

//Daniel

Sent from my iPad

On 12 jun 2012, at 18:27, Mike Trpcic
reply@reply.github.com
wrote:
