### ISSUE TITLE
Execution on page load only in Chrome

### ISSUE THREAD

**Issue by GRardB** [mtrpcic/pathjs#31]
I'm using PathJS's HTML5 pushState capability in an application. I want to be able to trigger actions not only when the user explicitly clicks on a link/form element, but also when the user goes to that page. For example: If the user goes to example.com/do/something, that should be the same as if they went to example.com and clicked a link that triggered "do/something." This is working for me in Chrome, but not Safari, Firefox, or Opera. Even if this is not the intended behavior, it is an inconsistency.

Is this a problem with PathJS or the implementation of the History API? I feel like it must be the former, since Backbone.js can do what I'm trying to do, right?

Thanks,
Gerard

**Comment by mtrpcic** [comment]
Right now, PathJS doesn't support this.  The idea was that it would be used for client-side routing, and if a user went to that fully qualified url, the server would render the expected content entirely.  What you can do in your `$(document).ready()` method (assuming you're using jQuery), is this:

```
if(window.location.pathname != "/"){
    Path.history.pushState(null, null, window.location.pathname);
}
```

I hope to fix this (well, make it an option) in an upcoming version of PathJS

**Comment by GRardB** [comment]
Thanks for the response! I actually did end up doing something similar to that. Although, I did find it strange that the functionality existed in Chrome, but not any other browser.
