### ISSUE TITLE
Trigger a hashchange

### ISSUE THREAD

**Issue by Darcbar** [mtrpcic/pathjs#43]
Is there any way to trigger a hashchange without a click?

**Comment by syphoxy** [comment]
if you're using HTML5 mode (automatically degrades to use hash in URL), you can use `Path.history.pushState({}, "", href)` where `href` is a reference to the URL you want to change the URL to.

if you're not using HTML5 mode, you can simply change the value of `window.location.hash = href` where `href` is a reference to the URL you want to change the URL to.

I hope this helps.

**Comment by Darcbar** [comment]
Great thanks
