### ISSUE TITLE
Documentation Update Suggestion

### ISSUE THREAD

**Issue by jeffdeville** [mtrpcic/pathjs#6]
Hey Mike,
Thanks for puting this together.  I am using it on a site where I want to have Google Analytics attached to each 'page'.  It was of course very simple with the AoP components, though I had to call GA slightly differently.

_gaq.push(['_trackPageview', document.location.href])

instead of:

_gaq.push(['_trackPageview'])

Then I just added an on enter block to handle the logging.  I think GA is a common enough thing to use, that it might be worthwhile to include some simple instructions like this in the markdown.

Thanks Mike!
Jeff

**Comment by mtrpcic** [comment]
Thanks for the suggestion Jeff.  I'll be adding this to the documentation and/or wiki as soon as I get some spare time.

I'm glad you're liking PathJS so far.

**Comment by mtrpcic** [comment]
This has been added to the wiki [here](https://github.com/mtrpcic/pathjs/wiki/Integrating-Google-Analytics).  The wiki will be further updated to include more examples, and this particular page will be updated to include support for the HTML5 History API.
