### ISSUE TITLE
pushState

### ISSUE THREAD

**Issue by bhellman1** [mtrpcic/pathjs#8]
Would there be a way to use pathJS with HTML5's pushState to keep the URLs clean? Thoughts?

**Comment by mtrpcic** [comment]
This is a forthcoming feature, as noted in the "Next Steps" section of the README.  I will update and close this issue when that feature has been implement.  Please note that I am in the midst of moving, and it may take a while for me to find some spare time to work on PathJS in the coming weeks.

**Comment by bhellman1** [comment]
missed that, thanks for pointing that out. That will be powerful! good luck with the move.

**Comment by Charuru** [comment]
Have we ETA?

**Comment by mtrpcic** [comment]
Unfortunately there is no ETA.  I know what has to be done to implement the feature, but I'm just lacking the time right now to get it done.  Development will start up again on the project within the week, and the feature should be implemented sometime next week.

**Comment by mtrpcic** [comment]
This functionality has been completed and committed as version 0.7.
