### ISSUE TITLE
Fails in IE7

### ISSUE THREAD

**Issue by benknight** [mtrpcic/pathjs#9]
After implementing pathjs on a site and seeing the rescue method being called for all paths, I checked the tests and they all fail in IE7.

**Comment by mtrpcic** [comment]
I'll see if I can find a Virtual Machine running IE7 today to confirm and fix.  Is it only IE7, or IE8 in Compatibility Mode as well?

**Comment by mtrpcic** [comment]
This has been Fixed in PathJS Version 0.6.5 (Latest as of this comment).  The issue was the method by which I was accessing characters in a string.  Thanks for the feedback :)
